import { useState } from "react";
import { listDocs, updateDoc, Query } from "@/lib/appwrite";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Shield, Ban, CheckCircle, AlertTriangle } from "lucide-react";
import { toast } from "sonner";
const TC = { low: "bg-yellow-500/20 text-yellow-400 border-yellow-500/30", medium: "bg-blue-500/20 text-blue-400 border-blue-500/30", high: "bg-green-500/20 text-green-400 border-green-500/30" };
export default function AdminTrustManager() {
  const qc = useQueryClient();
  const { data: profiles = [] } = useQuery({ queryKey: ["admin-profiles"], queryFn: () => listDocs("profiles", [Query.orderDesc("$createdAt"), Query.limit(500)]) });
  const { data: allSubs = [] } = useQuery({ queryKey: ["admin-all-subs"], queryFn: () => listDocs("gmail_submissions", [Query.limit(5000)]) });
  const getStats = email => { const us = allSubs.filter(s => s.submitted_by === email); const t = us.length, a = us.filter(s => s.status === "approved").length, r = us.filter(s => s.status === "rejected").length; return { total: t, approved: a, rejected: r, rate: t > 0 ? Math.round((r / t) * 100) : 0 }; };
  const updateTrust = async (id, level) => { await updateDoc("profiles", id, { trust_level: level }); qc.invalidateQueries({ queryKey: ["admin-profiles"] }); toast.success(`Trust set to ${level}`); };
  const toggleBan = async (id, cur) => { await updateDoc("profiles", id, { is_banned: !cur, ban_reason: !cur ? "Banned by admin" : "", is_restricted: false }); qc.invalidateQueries({ queryKey: ["admin-profiles"] }); toast.success(cur ? "Unbanned" : "Banned"); };
  const toggleRestrict = async (id, cur) => { await updateDoc("profiles", id, { is_restricted: !cur }); qc.invalidateQueries({ queryKey: ["admin-profiles"] }); toast.success(cur ? "Removed" : "Restricted"); };
  return <div className="space-y-3"><p className="text-sm text-muted-foreground">{profiles.length} users</p>{profiles.map(p => { const s = getStats(p.email); return <div key={p.$id} className="bg-card border border-border rounded-xl p-4 space-y-3"><div className="flex items-center justify-between flex-wrap gap-2"><div><p className="text-sm font-medium">{p.email}</p><p className="text-xs text-muted-foreground">{p.full_name}</p></div><div className="flex items-center gap-2"><Badge variant="outline" className={`${TC[p.trust_level] || TC.low} border text-xs`}>{p.trust_level}</Badge>{p.is_banned && <Badge className="bg-red-500/20 text-red-400 border-red-500/30 border text-xs"><Ban className="w-3 h-3 mr-1" />Banned</Badge>}{p.is_restricted && <Badge className="bg-orange-500/20 text-orange-400 border-orange-500/30 border text-xs"><AlertTriangle className="w-3 h-3 mr-1" />Restricted</Badge>}</div></div><div className="flex gap-4 text-xs"><span>Approved: <span className="text-green-400">{s.approved}</span></span><span>Rejected: <span className="text-red-400">{s.rejected}</span></span><span>Rate: <span className={s.rate > 40 ? "text-red-400" : "text-muted-foreground"}>{s.rate}%</span></span></div><div className="flex flex-wrap gap-2">{["low", "medium", "high"].map(l => <Button key={l} size="sm" variant={p.trust_level === l ? "default" : "outline"} onClick={() => updateTrust(p.$id, l)} className={`text-xs capitalize ${p.trust_level === l ? "bg-primary text-primary-foreground" : ""}`}>{l}</Button>)}<Button size="sm" variant="outline" onClick={() => toggleBan(p.$id, p.is_banned)} className={`text-xs ${p.is_banned ? "border-green-500/30 text-green-400" : "border-red-500/30 text-red-400"}`}>{p.is_banned ? <><CheckCircle className="w-3 h-3 mr-1" />Unban</> : <><Ban className="w-3 h-3 mr-1" />Ban</>}</Button><Button size="sm" variant="outline" onClick={() => toggleRestrict(p.$id, p.is_restricted)} className="text-xs border-orange-500/30 text-orange-400">{p.is_restricted ? "Unrestrict" : "Restrict"}</Button></div></div>; })}</div>;
}
