import { useState, useRef, useEffect } from "react";
import { invokeGroq } from "@/lib/groq";
import { X, Send, Loader2, Bot } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

const WA_LINK = "https://chat.whatsapp.com/JmSWDINefIA5cBLEon0Dz1?mode=gi_t";

const SYSTEM_PROMPT = `You are GPay Bot, the friendly assistant for GmailPay. You help users understand how to earn money on the platform.

**HOW GMAILPAY WORKS — Step by Step:**

1. **Sign Up** — Create an account on GmailPay with your email and password.
2. **Go to Dashboard** — After signing in, you land on the Dashboard.
3. **Reserve Usernames** — In the "Reserve Usernames" section, select how many usernames you want (you can generate up to 20 per day). Click "Generate" to get unique Gmail usernames.
4. **Create New Gmail Accounts** — Open the Gmail app on your phone. Tap "Create account" to make a BRAND NEW Gmail. Use the username GmailPay gave you as the Gmail address, and set the password to **iffyboi77**. That's it — just create it. You do NOT need to log into it or do anything else with it.
5. **Submit Your Gmails** — Go back to GmailPay Dashboard, scroll to the "Submit Gmails" section. Paste the Gmail username(s) you just created (one per line). Click Submit.
6. **Wait for Approval** — Your submissions go to review. Check the "Submissions" tab to track status (Pending → Approved or Rejected).
7. **Get Paid** — Each approved Gmail earns you **₦200**. Your balance updates automatically.
8. **Withdraw** — Once your balance reaches the minimum of **₦1,000**, you can withdraw to your bank account.

**BONUSES & REWARDS:**
- Earn a **₦500 bonus** when you reach 50 approved Gmails
- **Referral Program**: Share your referral link from the "Referrals" tab. When someone signs up using your link, you earn bonus money for every Gmail they submit.

**IMPORTANT RULES:**
- ALL Gmails MUST use the password: **iffyboi77**
- Only NEW Gmails count — do not submit old or existing accounts
- Use only the usernames generated by GmailPay
- Submitting fake or duplicate Gmails will result in rejection and possible ban

**TRUST LEVELS:**
- New users start at "low" trust level
- As you submit more approved Gmails, your trust level increases
- Higher trust = more daily submissions allowed

CRITICAL: Users do NOT need to "log in" to the Gmail accounts. They just CREATE the new Gmail in the Gmail app using the username + password iffyboi77, then come back to GmailPay and SUBMIT the username. That's all. Do NOT tell users to log in, verify, or do anything with the Gmail account after creating it.

Be helpful, friendly, and encouraging. Answer questions clearly and guide users through the process. Keep responses concise and use simple language. If someone asks something unrelated to GmailPay, politely redirect them.`;

export default function GPayBot() {
  const [open, setOpen] = useState(false);
  const [msgs, setMsgs] = useState([
    { role: "bot", content: "Welcome to GPay! \ud83d\udc4b I can help you understand how to earn money here. Ask me anything!" },
  ]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const endRef = useRef(null);

  useEffect(() => {
    endRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [msgs]);

  const send = async () => {
    if (!input.trim() || loading) return;
    const m = input.trim();
    setInput("");
    setMsgs((p) => [...p, { role: "user", content: m }]);
    setLoading(true);
    try {
      const r = await invokeGroq(
        SYSTEM_PROMPT + "\n\nUser question: " + m
      );
      const responseWithLink = r + "\n\n\ud83d\udce2 Join our WhatsApp group for updates: " + WA_LINK;
      setMsgs((p) => [...p, { role: "bot", content: responseWithLink }]);
    } catch (err) {
      setMsgs((p) => [...p, { role: "bot", content: "Sorry, I had trouble responding. Please try again or join our WhatsApp group for help: " + WA_LINK }]);
    }
    setLoading(false);
  };

  return (
    <>
      {!open && (
        <motion.button
          initial={{ scale: 0 }}
          animate={{ scale: 1 }}
          onClick={() => setOpen(true)}
          className="fixed bottom-6 right-6 z-50 w-12 h-12 rounded-full bg-primary text-primary-foreground flex items-center justify-center shadow-lg hover:scale-105 transition-transform"
        >
          <Bot className="w-5 h-5" />
        </motion.button>
      )}
      <AnimatePresence>
        {open && (
          <motion.div
            initial={{ opacity: 0, y: 50, scale: 0.9 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 50, scale: 0.9 }}
            className="fixed bottom-6 right-6 z-50 w-[340px] max-w-[calc(100vw-3rem)] bg-card border border-border rounded-xl shadow-2xl overflow-hidden flex flex-col"
            style={{ height: "420px" }}
          >
            <div className="flex items-center justify-between p-4 border-b border-border bg-secondary/50">
              <div className="flex items-center gap-2">
                <Bot className="w-4 h-4 text-primary" />
                <p className="text-sm font-bold">
                  GPay{" "}
                  <span className="text-primary text-xs font-normal">BOT</span>
                </p>
              </div>
              <button onClick={() => setOpen(false)}>
                <X className="w-5 h-5 text-muted-foreground" />
              </button>
            </div>
            <div className="flex-1 overflow-y-auto p-4 space-y-3">
              {msgs.map((m, i) => (
                <div
                  key={i}
                  className={`flex ${
                    m.role === "user" ? "justify-end" : "justify-start"
                  }`}
                >
                  <div
                    className={`max-w-[85%] rounded-xl px-3 py-2 text-sm whitespace-pre-wrap ${
                      m.role === "user" ? "bg-primary/20" : "bg-secondary"
                    }`}
                  >
                    {m.content.split(WA_LINK).length > 1 ? (
                      <>
                        {m.content.split(WA_LINK)[0]}
                        <a
                          href={WA_LINK}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-[#25D366] underline font-medium break-all"
                        >
                          Join WhatsApp Group
                        </a>
                      </>
                    ) : (
                      m.content
                    )}
                  </div>
                </div>
              ))}
              {loading && (
                <div className="flex justify-start">
                  <div className="bg-secondary rounded-xl px-3 py-2">
                    <Loader2 className="w-4 h-4 animate-spin text-primary" />
                  </div>
                </div>
              )}
              <div ref={endRef} />
            </div>
            <div className="p-3 border-t border-border flex gap-2">
              <input
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && send()}
                placeholder="Type a message..."
                className="flex-1 bg-secondary border border-border rounded-lg px-3 py-2 text-sm"
              />
              <button
                onClick={send}
                disabled={loading}
                className="p-2 rounded-lg bg-primary text-primary-foreground"
              >
                <Send className="w-4 h-4" />
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}
